### ISSUE TITLE
Is this project not maintained anymore?

### ISSUE THREAD

**Issue by nasifimtiazohi** [nice-registry/all-the-package-names#25]
I see the last commit is in 2019.
Can you suggest me where I can get the current list of most downloaded npm packages?

**Comment by zarianec** [comment]
Hi @nasifimtiazohi, we know about this issue and already planned fix for it.

Currently it's blocked by https://github.com/nice-registry/all-the-package-repos/pull/36 but I hope we will fix it soon.
