### ISSUE TITLE
Seems like the auto update has stopped

### ISSUE THREAD

**Issue by scriptcoded** [nice-registry/all-the-package-names#30]
Hi!

Cool stuff this here! Seems like the automatic grabbing has stopped though? Is that correct?

**Comment by MartinKolarik** [comment]
Indeed I see the update process [broke](https://github.com/nice-registry/all-the-package-repos/actions). We'll fix it and set up some monitoring for it so that it doesn't happen in the future.

**Comment by MartinKolarik** [comment]
Fix and monitoring set up.
