### ISSUE TITLE
only grab packages after 72 hour window

### ISSUE THREAD

**Issue by PatrickJS** [nice-registry/all-the-package-names#39]
NPM has a 72 hour unpublish policy which means the list may not be correct or some packages were never intended to be captured. I think it's fair to say delay the list generation by 72 to avoid this.

https://docs.npmjs.com/policies/unpublish

**Comment by MartinKolarik** [comment]
The goal of this project is to provide as up-to-date information as possible and the unpublish policy isn't really an issue here. If your use case requires older data, you can easily query the npm registry for a list of versions of this package, and select any of the older versions based on the publish date.
