### ISSUE TITLE
line 20 makes lodash redundant?

### ISSUE THREAD

**Issue by WebReflection** [nice-registry/all-the-package-names#7]
Your is a lovely package and this is not a real issue, rather curiosity, but I was wondering the reason behind lodash as dependency.

In line 20
https://github.com/nice-registry/all-the-package-names/blob/336988664034a8220e6dd1d24fbe9795d157eb1f/script/build#L20

you ignore `falsy` values like [compact](https://lodash.com/docs/#compact) would do, with a check on `name.length` that is also not needed since empty strings are falsy already so `if ('') { alert(1); }` never happens, and you filter duplicates via `array.includes(name)` like [uniq](https://lodash.com/docs/#uniq), and after you get again all values you had before.

Not only you could've simply used an `if (name) names.add(name)` having `names` as [new Set](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Set) instead of an Array, you could also easily get rid of lodash as dependency.

You know, you're somehow responsible for its score in the top 10 😄 

Am I missing something obvious in your code?

Would be so kind to explain me why you need lodash here?

**Comment by zeke** [comment]
Hey there. Somehow I missed this issue back when you created it. If you would like to submit a PR that change this, I'd be open to it. Thanks!

**Comment by WebReflection** [comment]
sorry, not as important, no time for PR.

closing this as personal github issues clean-up duty

**Comment by zeke** [comment]
> personal github issues clean-up duty

Feels good, right?

Off-topic: @groundwater did manage to get Electron building on ARM64. I was supposed to remind you when that happened, right?

**Comment by WebReflection** [comment]
good to know, thanks.

Do you know if also `npm i electron` works on ARM64 ?

**Comment by zeke** [comment]
We started including ARM64 builds as of 1.8.1, which hasn't yet stabilized: https://github.com/electron/electron/releases/tag/v1.8.1

You can install the latest beta with `npm i -D electron@beta`

**Comment by WebReflection** [comment]
I need my SBCs with me, which won't happen before middle January so ... thanks for the heads up, I'll come back!
