### ISSUE TITLE
Automatic updates have stopped

### ISSUE THREAD

**Issue by dmfrancisco** [nice-registry/all-the-package-names#8]
Just wanted to bring this to your attention in case you didn't notice. It seems the last update was 20 days ago. Thank you for making this project 👏

**Comment by zeke** [comment]
Uh-oh. Thanks for letting me know.

**Comment by zeke** [comment]
```
+ npm version minor -m 'bump minor to %s'
v1.3383.0
+ npm publish
npm ERR! publish Failed PUT 403
npm ERR! Linux 3.13.0-133-generic
npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "publish"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code E403

npm ERR! You cannot publish over the previously published version 1.3383.0. : all-the-package-names
```

This happens occasionally when a publish makes it to npm, but the `git push` doesn't make it to GitHub. I pushed https://github.com/nice-registry/all-the-package-names/commit/7a8bf38a55fbba5b04de75403c45cb4daf079154 to master, and the problem should correct itself in the next day. Let's see...

**Comment by dmfrancisco** [comment]
Seems like it worked 👍 Thanks again!

**Comment by dmfrancisco** [comment]
@zeke In case you didn't notice, it seems the updates have stopped again 😶

**Comment by zeke** [comment]
Yeah sheesh. Process might be running out of memory? Investigating...

**Comment by zeke** [comment]
I pushed up a broken change. Fixed now, and rerunning the build. There are over 700,000 packages now!

**Comment by dmfrancisco** [comment]
Wow, great! Thank you for dedicating time to this 🙌

**Comment by zeke** [comment]
New version just got published: https://github.com/nice-registry/all-the-package-names/commits/master

Not actually 700,000, but 621759. I guess that means there are 84,575 invalid packages emitted by replicate.npmjs.com.
